[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "nix_cuda_test"
dynamic = ["version"]
authors = [{ name = "Connor Baker", email = "connorbaker01@gmail.com" }]
description = "Test project for Nix CUDA support"
readme = "README.md"
requires-python = ">=3.10"
keywords = ["nix", "machine", "learning", "torch", "gpu", "test", "cuda"]
license = { text = "BSD-3-Clause" }
classifiers = ["Programming Language :: Python :: 3"]
dependencies = [
    "click>=8.1.3",
    "pydantic>=1.10.8",
    "torch>=2.0",
    "torchvision>=0.15.2",
    "triton>=2.0",
]

[tool.black]
line-length = 120

[tool.ruff]
select = ["E", "F", "B"]
# Set line length to 88 characters
line-length = 120

[tool.setuptools]
packages = ["nix_cuda_test"]

[tool.setuptools.dynamic]
version = { attr = "nix_cuda_test.__version__" }
